#!/home/jperry/.asdf/shims/ruby

require File.join(File.dirname(__FILE__), 'polypatch')

def print_usage
  puts "Usage: polypatch [patchname] [path]"
end

if ARGV.length < 2
  print_usage
  exit
end

patchfile, basepath = ARGV


if !File.exists?(patchfile)
  puts "Patchfile \"#{patch}\" does not exist\n"
  print_usage
  exit
end

patch = PolyPatch::PatchFile.new(patchfile)
patch.apply(basepath)

puts "Done!"